apiVersion: v1
kind: Service
metadata:
  name: { { include "postgres-chart.fullname" . } }
  labels:
    app: { { include "postgres-chart.name" . } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: { { include "postgres-chart.name" . } }
