replicaCount: 1

image:
  repository: maybetuandat/vdt_db
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5432
  nodePort: 30432

persistence:
  enabled: true
  storageClass: "standard" 
  size: 5Gi

env:
  POSTGRES_DB: student_management
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "123456"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Thêm probe để kiểm tra health
healthCheck:
  enabled: true