replicaCount: 1

image:
  repository: postgres
  tag: "14"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  storageClass: ""
  size: 1Gi

env:
  POSTGRES_DB: vdt_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "123456"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
