replicaCount: 1

image:
  repository: maybetuandat/vdt_db
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5432
  nodePort: 30432

persistence:
  enabled: true
  storageClass: "standard" 
  size: 5Gi

env:
  POSTGRES_DB: student_management
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "123456"


healthCheck:
  enabled: true